[package]
name = "meme-nft"
version = "1.0.0"
authors = []

[addresses]
meme_nft = "0x64f6979360f13452cd87d367490075326f8e73d21a8bc746695f8d15e12e2016"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
