[package]
name = "meme-nft"
version = "1.0.0"
authors = []

[addresses]
meme_nft = "0x26198839dbbf26dcd13e1ea47702e9dc7a08604486033d6ac513cee981309ea9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
